server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

## Enable `conditions evaluation report`
#debug: true

spring:
  profiles:
    active: dev
  application:
    name: OnFood
  jpa:
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/liquibase-master.xml
    # TIP: for oracle, table's name must be capital!
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb1.localdomain
    username: u_onfood
    password: onFood

decorator:
  datasource:
    datasource-proxy:
      query:
        log-level: INFO

---

spring:
  config:
    activate:
      on-profile: test-jwt
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:test;sql.syntax_ora=true
    username: sa

decorator:
  datasource:
    datasource-proxy:
      query:
        log-level: INFO

on-food:
  security:
    token-media: header

---

spring:
  config:
    activate:
      on-profile: test-cookie
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:test;sql.syntax_ora=true
    username: sa

decorator:
  datasource:
    datasource-proxy:
      query:
        log-level: INFO

on-food:
  security:
    token-media: cookie
    token-key: token

