spring:
  application:
    name: OnFood
  jpa:
    database: hsql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  datasource:
    url: jdbc:hsqldb:mem:test
    username: sa
  #    password: ""

  liquibase:
    change-log: classpath:db/changelog/liquibase-master.xml
    database-change-log-table: z_liq_changelog
    database-change-log-lock-table: z_liq_changelog_lock

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: onfood1
        hostname: onfood.example.com
        port: 80
        metadata:
          branch: main
        tags:
          - sample

## Enable `conditions evaluation report`
#debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
