spring:
  application:
    name: OnFood
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
#    password: ""
